// cx_erfc.hpp — constexpr erfc via a Taylor series (small x) and Chebyshev
// fits of exp(x²)·erfc(x) (larger x).
//
// Algorithm
// ---------
// x < 0: erfc(x) = 2 - erfc(-x), which loses nothing since erfc(-x) < 1.
//
// 0 < x < 0.5: erfc(x) = 1 - erf(x), with
//   erf(x) = (2/√π) · x · Σ_{n=0}^{N} t^n / (n! · (2n+1)),   t = -x²
// in Horner form. erf(x) < 0.53 here, so the subtraction loses little.
//
// 0.5 ≤ x ≤ 30: erfc(x) = exp(-x²) · g(x), where g(x) = exp(x²)·erfc(x) is
// smooth and slowly varying (it falls from 0.6 at 0.5 like 1/(x·√π)). g is
// a Chebyshev series on each dyadic interval [0.5, 1], [1, 2], …, [16, 32],
// of at most 25 terms (gen_erfc_chebyshev.py fits them to 2^-60), summed by
// Clenshaw's recurrence. Mapping x to [-1, 1] is exact on a dyadic interval
// (Sterbenz). exp(-x²) amplifies the rounding of x² by x², so x² is split
// exactly into hi + lo first (Veltkamp/Dekker).
//
// Special cases: NaN → NaN, +∞ → 0, -∞ → 2, 0 → 1.
//
// Accuracy: within a few ulp of std::erfc (see tests/cx_std/cx_std.t.cpp).

#ifndef CX_STD_CX_ERFC_HPP
#define CX_STD_CX_ERFC_HPP

#include "cx_exp.hpp"

#include <cstddef>
#include <limits>
#include <numbers>
#include <type_traits>

namespace cx {
namespace detail {

constexpr std::size_t kErfTerms = 28; // Taylor terms; ample for |x| < 0.5

// ---------------------------------------------------------------------------
// Taylor path: erf(x) = (2/√π)·x · Σ_{n=0}^{N} (-x²)^n / (n!·(2n+1))
// Horner kernel: computes Σ_{n=k}^{N} t^(n-k) / (n!·(2n+1))
// where t = -x², initial call n=0.
// ---------------------------------------------------------------------------
template <typename T>
constexpr T erf_horner(T t, T factorial_n, std::size_t n, std::size_t N) {
  return n >= N ? T(0)
                : T(1) / (factorial_n * static_cast<T>(2 * n + 1)) +
                      t * erf_horner(t, factorial_n * static_cast<T>(n + 1),
                                     n + 1, N);
}

template <typename T> constexpr T erfc_taylor(T x) {
  constexpr T two_over_sqrt_pi = T(2) * std::numbers::inv_sqrtpi_v<T>;
  T t = -x * x;
  T erf_x = two_over_sqrt_pi * x * erf_horner(t, T(1), 0, kErfTerms);
  return T(1) - erf_x;
}

// ---------------------------------------------------------------------------
// Chebyshev path, 0.5 ≤ x ≤ 30. Generated by gen_erfc_chebyshev.py: piece i
// is g on [2^(i-1), 2^i] in u = (x - 0.75·2^i) / (0.25·2^i), c[0] halved.
// ---------------------------------------------------------------------------
inline constexpr std::size_t kErfcPieces = 6;
inline constexpr std::size_t kErfcMaxTerms = 25;
inline constexpr std::size_t erfc_terms[kErfcPieces] = {16, 19, 21, 24, 25, 25};
inline constexpr double erfc_chebyshev[kErfcPieces][kErfcMaxTerms] = {
    // [0.5, 1.0]
    {0.5142540300448141, -0.09353436157631646, 0.007349543567965961,
     -0.0005170287683170955, 3.327489181039832e-05, -1.9877609419315706e-06,
     1.1137198399251981e-07, -5.898649609389129e-09, 2.9712990142852805e-10,
     -1.430488185776257e-11, 6.608616284265576e-13, -2.939555289997837e-14,
     1.2625028540336645e-15, -5.2483534858603674e-17, 2.116281534737731e-18,
     -8.280881761800545e-20},
    // [1.0, 2.0]
    {0.331427281639452, -0.0850021377067432, 0.009951127341466115,
     -0.0010810888102208325, 0.0001102324363119495, -1.0636830518218601e-05,
     9.775012680479055e-07, -8.597922867888315e-08, 7.2677084117248425e-09,
     -5.923543840592542e-10, 4.6683928572294154e-11, -3.56612770156775e-12,
     2.6458779519104523e-13, -1.9101658673527494e-14, 1.3439765884785826e-15,
     -9.228790546933531e-17, 6.192672716113081e-18, -4.065160636251211e-19,
     2.6032348474778433e-20},
    // [2.0, 4.0]
    {0.1874295690262241,      -0.05794652883669097,    0.008595247387396534,
     -0.0012284613640242594,  0.00016974366686180488,  -2.2738329337044562e-05,
     2.959844378804878e-06,   -3.7513575581379714e-07, 4.6372828761738244e-08,
     -5.599455392564088e-09,  6.613160896679916e-10,   -7.648271522199816e-11,
     8.670904325876594e-12,   -9.645456274382108e-13,  1.053682795936055e-13,
     -1.1312630906752193e-14, 1.1945180668243186e-15,  -1.241310742461068e-16,
     1.2702452367108009e-17,  -1.2806106388503558e-18, 1.260873261981161e-19},
    // [4.0, 8.0]
    {0.09799557556862198,     -0.03261716242283879,   0.005354444513048941,
     -0.0008675085617618387,  0.0001387834577332989,  -2.1933248302183236e-05,
     3.425716824410705e-06,   -5.289955530513349e-07, 8.079076527537946e-08,
     -1.2207511691612988e-08, 1.8255151508559988e-09, -2.7024969193563974e-10,
     3.961752303537055e-11,   -5.752619043200236e-12, 8.275752891382595e-13,
     -1.179816774444541e-13,  1.6671816868045445e-14, -2.3356287455454187e-15,
     3.2446200044034663e-16,  -4.470390165945688e-17, 6.1098005449787135e-18,
     -8.284786657151921e-19,  1.114434129682231e-19,  -1.462721949043457e-20},
    // [8.0, 16.0]
    {0.0496402148021428,      -0.016897808070160118,  0.0028652408255077657,
     -0.00048403293647937437, 8.146859582420295e-05,  -1.3662340878975885e-05,
     2.2829539932731383e-06,  -3.801224444355858e-07, 6.30697220062995e-08,
     -1.0428112493713957e-08, 1.7182796156078595e-09, -2.8216353600775824e-10,
     4.617874055248115e-11,   -7.532381371020102e-12, 1.2245769587090083e-12,
     -1.984347172176958e-13,  3.205095192594639e-14,  -5.160235538551082e-15,
     8.281647822466564e-16,   -1.324938360719887e-16, 2.1130950988533038e-17,
     -3.35969014742039e-18,   5.325280363689119e-19,  -8.410402551460475e-20,
     1.2932585098349791e-20},
    // [16.0, 32.0]
    {0.024905097353781745,    -0.008528727616881514,   0.0014589152524793687,
     -0.00024931992222736865, 4.256633635866193e-05,   -7.2603774484576065e-06,
     1.2371917610694735e-06,  -2.1062066549245407e-07, 3.5822205670485775e-08,
     -6.086845487205534e-09,  1.0332896203608712e-09,  -1.7524389842807873e-10,
     2.969313145827533e-11,   -5.026463705306691e-12,  8.500877273856693e-13,
     -1.4363516245993166e-13, 2.4246820463541814e-14,  -4.089281370833025e-15,
     6.890306193061495e-16,   -1.159926662602274e-16,  1.9508512730767636e-17,
     -3.2780857012650876e-18, 5.503149704554036e-19,   -9.22328059203042e-20,
     1.5034928473194643e-20},
};

// exp(-x²), with x² = hi + lo exactly.
template <typename T> constexpr T exp_minus_square(T x) {
  constexpr T splitter =
      pow2<T>((std::numeric_limits<T>::digits + 1) / 2) + T(1);
  const T c = splitter * x;
  const T hi = c - (c - x);
  const T lo = x - hi;
  return cx::exp(-(hi * hi)) * cx::exp(-(T(2) * hi * lo + lo * lo));
}

// g(x) = exp(x²)·erfc(x) by Clenshaw's recurrence on x's piece.
template <typename T> constexpr T erfc_scaled(T x) {
  std::size_t i = 0;
  T top = T(1); // 2^i, the piece's upper end
  while (i + 1 < kErfcPieces && x >= top) {
    ++i;
    top *= T(2);
  }
  const T u = (x - T(0.75) * top) * (T(4) / top); // exact: powers of two
  const double *c = erfc_chebyshev[i];
  T b1 = T(0), b2 = T(0);
  for (std::size_t k = erfc_terms[i] - 1; k >= 1; --k) {
    const T b0 = static_cast<T>(c[k]) + T(2) * u * b1 - b2;
    b2 = b1;
    b1 = b0;
  }
  return static_cast<T>(c[0]) + u * b1 - b2;
}

template <typename T> constexpr T erfc_large(T x) {
  return exp_minus_square(x) * erfc_scaled(x);
}

// Core: x is finite and non-zero.
template <typename T> constexpr T erfc_core(T x) {
  if (x < T(0))
    return T(2) - erfc_core(-x);
  if (x > T(30)) // underflows: erfc(27.3) is below the smallest double
    return T(0);
  return x < T(0.5) ? erfc_taylor(x) : erfc_large(x);
}

} // namespace detail

// constexpr erfc for floating-point types.
template <typename T, std::enable_if_t<std::is_floating_point_v<T>, int> = 0>
constexpr T erfc(T x) {
  return x != x                                     ? x    // NaN → NaN
         : x == +std::numeric_limits<T>::infinity() ? T(0) // +∞  → 0
         : x == -std::numeric_limits<T>::infinity() ? T(2) // -∞  → 2
         : x == T(0)                                ? T(1) //  0  → 1
                                                    : detail::erfc_core(x);
}

// Integral overload: promote to double.
template <typename T, std::enable_if_t<std::is_integral_v<T>, int> = 0>
constexpr double erfc(T x) {
  return cx::erfc(static_cast<double>(x));
}

} // namespace cx

#endif // CX_STD_CX_ERFC_HPP
