#!/usr/bin/env python3
"""Write the CMake file that gives each CTest test what its directives say.

CMake runs this once at configure time (read_test_directives in
test_simple_cmake.cmake) over every test it registers, so that CTest builds
a test with the same flags as run_tests.py, and rejects the same invalid
directives, from the same reader (source_directives.read_test_directives):

    test_directives_cmake.py write --compiler <clang|gcc> --output <file.cmake>
        [--must-compile <file.cpp>...] [--must-fail <file.cpp>...]

For each test, the output sets source file properties:

- COMPILE_FLAGS: the test's TEST-FLAGS for the compiler, then, for a test
  that must fail to compile, compile_fail_check.DIAGNOSTIC_FLAGS, last so
  that they win; shell-quoted, as the build tool passes the string to the
  shell. (Source flags come after CMAKE_CXX_FLAGS and the target's own
  options on the command line. A source's COMPILE_OPTIONS doesn't honour
  `SHELL:`, so it would split or merge flags that are written together.)
- TEST_DIRECTIVE_ERROR: why the test's directives are invalid, or empty.

test_simple_cmake.cmake registers a test with an error, instead of building
it, as a test that runs

    test_directives_cmake.py report --compiler <clang|gcc> --source <file.cpp> [--must-fail]

which prints why its directives are invalid and fails. (It fails even if
they have been fixed since: the test can only pass once CMake has re-read
them, which building does.)
"""

from __future__ import annotations

import argparse
import shlex
import sys
from pathlib import Path

if __package__:
    from . import compile_fail_check, source_directives
else:  # run as a script; its directory isn't on sys.path under `python3 -P`
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import compile_fail_check
    import source_directives


def cmake_argument(value: str) -> str:
    """`value` as a CMake bracket argument, which nothing in it can end
    early or expand."""
    equals = "="
    # The argument ends at the first `]=...=]`, which must be the closing one.
    while f"{value}]{equals}]".find(f"]{equals}]") != len(value):
        equals += "="
    return f"[{equals}[{value}]{equals}]"


def write(paths: list[tuple[Path, bool]], compiler: str, output: Path) -> None:
    """Write the CMake file for the tests `paths` (path, must_fail)."""
    text = "# Generated by test_directives_cmake.py; do not edit.\n" + "".join(
        source_properties(path, compiler, must_fail) for path, must_fail in paths
    )
    # Rewritten only when it changes, so CMake doesn't see a new file.
    if not output.exists() or output.read_text(encoding="utf-8") != text:
        output.write_text(text, encoding="utf-8")


def report(path: Path, compiler: str, must_fail: bool) -> str:
    """Why the directives of the test at `path` are invalid."""
    try:
        source_directives.load_test_directives(path, compiler, must_fail)
    except source_directives.DirectiveError as error:
        return f"{path}: {error}"
    return (
        f"{path}: its directives were invalid when CMake read them; build "
        "(or re-run CMake) so that it reads them again"
    )


def source_properties(path: Path, compiler: str, must_fail: bool) -> str:
    """The set_property() calls for one test."""
    flags: list[str] = []
    message = ""
    try:
        directives = source_directives.load_test_directives(path, compiler, must_fail)
    except source_directives.DirectiveError as error:
        message = f"{path}: {error}"
    else:
        flags += directives.flags
        if must_fail:
            flags += compile_fail_check.DIAGNOSTIC_FLAGS
    source = cmake_argument(str(path))
    # (shlex.join needs Python 3.8.)
    compile_flags = " ".join(map(shlex.quote, flags))
    return (
        f"set_property(SOURCE {source} PROPERTY COMPILE_FLAGS"
        f" {cmake_argument(compile_flags)})\n"
        f"set_property(SOURCE {source} PROPERTY TEST_DIRECTIVE_ERROR"
        f" {cmake_argument(message)})\n"
    )


def main(argv: list[str] | None = None) -> int:
    # No docstring under `python3 -OO`.
    parser = argparse.ArgumentParser(
        description=__doc__.splitlines()[0] if __doc__ else None
    )
    commands = parser.add_subparsers(dest="command", required=True)
    write_parser = commands.add_parser("write")
    write_parser.add_argument("--output", type=Path, required=True)
    write_parser.add_argument("--must-compile", type=Path, nargs="*", default=[])
    write_parser.add_argument("--must-fail", type=Path, nargs="*", default=[])
    report_parser = commands.add_parser("report")
    report_parser.add_argument("--source", type=Path, required=True)
    report_parser.add_argument("--must-fail", action="store_true")
    for subparser in (write_parser, report_parser):
        subparser.add_argument(
            "--compiler", choices=source_directives.COMPILERS, required=True
        )
    args = parser.parse_args(argv)

    if args.command == "write":
        write(
            [(path, False) for path in args.must_compile]
            + [(path, True) for path in args.must_fail],
            args.compiler,
            args.output,
        )
        return 0
    print(report(args.source, args.compiler, args.must_fail))
    return 1


if __name__ == "__main__":
    sys.exit(main())
